package com.juliosburger.domain.events

enum class DomainEventType {
    CONVERSATION_STARTED,
    CONVERSATION_STATE_CHANGED,
    CONVERSATION_FINISHED,
    DRAFT_ORDER_CREATED,
    DRAFT_ORDER_UPDATED,
    DRAFT_ORDER_CONFIRMED,
    ORDER_ACCEPTED,
    ORDER_COOKING,
    ORDER_READY,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    CUSTOMER_MEMORY_UPDATED,
    BUSINESS_VOCABULARY_CREATED,
    BUSINESS_VOCABULARY_UPDATED,
    BUSINESS_VOCABULARY_DISABLED,
    RESTAURANT_OPENED,
    RESTAURANT_CLOSED,
    PROMOTION_ACTIVATED,
    PROMOTION_DEACTIVATED,
    COMPLAINT_CREATED
}
